Feature/friendshipv2
Mindo-Joseph/stay-in-touch pull request #7
Opened 2020-07-29 15:58 UTC by Mindo-Joseph

### What does this PR do?
- Update the friendship controller to prevent duplication of created friendships

### How can this project be tested?
- Run ```rspec spec/features/friendships_spec.rb```

2020-07-29 19:53 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for the effort put into this project so far.
Please, a bit more effort to move forward

1- In the user list, after sending a friendship request, I didn't see the two buttons for **accepting** or **rejecting** the friendship request in front of the user's name. They were only available once opening the user's profile. They must be available in the user's list

2- Look the Timeline from these two friends
**Alice Bar**
![Screenshot at 2020-07-29 18:42:17](https://user-images.githubusercontent.com/8848104/88845114-9836e980-d1db-11ea-916e-4da541a6f9dd.png)
**Bob Bar**
![Screenshot at 2020-07-29 18:42:39](https://user-images.githubusercontent.com/8848104/88845131-9ec56100-d1db-11ea-96af-3254855bff09.png)

You can notice from those two timelines are different.

3- Here is what we have from the console 
```rb
2.7.1 :001 > Friendship.all
  Friendship Load (0.4ms)  SELECT "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, user_id: 2, friend_id: 1, confirmed: true, created_at: "2020-07-29 17:38:47", updated_at: "2020-07-29 17:41:00">]> 
2.7.1 :002 >
```
In this milestone, you're supposed to implement the two rows friendship. So for these 2 users, the table is supposed to have two rows.

4- Read the comments left below.

5- Update the **integration tests**

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-29 19:53 UTC, maelfosso commented on app/views/users/index.html.erb
> +        <% end %>
That is what we call **logic in views**. I mean `if`, `if/else`, `if/elsif` and so on.
It should be implemented in **views helpers**

2020-07-29 19:53 UTC, maelfosso commented on app/views/users/index.html.erb
> +        <% if signed_in? && !Friendship.reacted?(current_user.id, user.id) && current_user != user %>
`Friendship.reacted?` is not good here.

2020-07-29 19:53 UTC, maelfosso commented on app/views/users/show.html.erb
> +       <% end %>
Use **views helpers** please

2020-07-29 19:53 UTC, maelfosso commented on app/views/shared/_user_posts.html.erb
> +<% end %>
Use **views helpers**

2020-07-30 00:30 UTC, edieatha commented
## TSE Recommendations Applied
* Remove logic from views with helpers and partials
* Update integration tests
* Add 2 records per pair of friendships

2020-07-30 00:35 UTC, rOluochKe requested changes
Hello Team
### The pr branch has conflicts that you need to solve before the project can be reviewed
### Make the changes and submit for another code review. Good luck!

By Raymond
Slack @iamraymond

2020-07-30 08:50 UTC, merged